name: school_bus_app
description: A unified mobile application for parents and drivers.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # TODO: Add required dependencies
  # supabase_flutter: ^1.0.0
  # google_maps_flutter: ^2.2.0
  # firebase_messaging: ^14.0.0
  # provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
